import { Property } from "./types";

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    slug: "penthouse-ocean-front-bello-horizonte",
    code: "SER-881",
    title: "Grand Penthouse Frente al Mar en Bello Horizonte",
    tagline: "Vistas panorámicas 360° al Caribe y la Sierra Nevada de Santa Marta",
    description:
      "Una joya de la arquitectura costera contemporánea en el sector más exclusivo de Bello Horizonte. Este penthouse dúplex cuenta con terrazas envolventes privadas, jacuzzi suspendido sobre el horizonte marino, ventanería termoacústica de piso a techo y acabados en mármol blanco italiano y maderas tropicales curadas. El edificio ofrece acceso directo a la playa, 3 piscinas infinitas, spa, helipuerto de emergencia y servicio de conserjería 24/7.",
    price: 3450000000,
    currency: "COP",
    adminFee: 1850000,
    operation: "venta",
    propertyType: "penthouse",
    status: "destacada",
    isFeatured: true,
    sectorId: "sec-bello-horizonte",
    sectorName: "Bello Horizonte",
    address: "Km 14 Vía Ciénaga, Edificio Terrazas del Mar",
    zone: "Santa Marta",
    coordinates: { lat: 11.1345, lng: -74.2285 },
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 3,
    builtArea: 385,
    privateArea: 350,
    floorNumber: 18,
    yearBuilt: 2023,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Vista directa al mar",
      "Frente a la playa",
      "Piscina infinity",
      "Jacuzzi privado",
      "Ascensor privado directo",
      "Gimnasio con vista al mar",
      "Completamente amoblado de diseñador",
      "Seguridad privada 24/7",
      "Zona BBQ en terraza",
      "Planta eléctrica total",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "LEAD_PENTHOUSE_BELLO_HORIZONTE",
    metaTitle: "Grand Penthouse Frente al Mar en Bello Horizonte | SERINMOBILIARIO",
    metaDescription:
      "Penthouse dúplex exclusivo de 385 m² en Bello Horizonte, Santa Marta. 4 suites, piscina privada y acceso directo a playa.",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "prop-2",
    slug: "apartamento-turistico-salguero-infinity",
    code: "SER-532",
    title: "Apartamento de Alta Renta Turística en Playa Salguero",
    tagline: "Licencia turística activa y ocupación superior al 82% anual comprobada",
    description:
      "Propiedad de inversión ideal con habilitación completa para plataformas como Airbnb y booking de lujo. Ubicado en primera línea de mar en Playa Salguero, este apartamento ofrece una terraza profunda con vista infinita al mar Caribe, cocina abierta italiana, carpintería arquitectónica y automatización domótica. El edificio opera como condo-hotel de 5 estrellas con piscinas climatizadas, restaurante gourmet, sauna húmedo y bar en el rooftop.",
    price: 1180000000,
    currency: "COP",
    adminFee: 690000,
    operation: "inversion",
    propertyType: "condohotel",
    status: "destacada",
    isFeatured: true,
    sectorId: "sec-playa-salguero",
    sectorName: "Playa Salguero",
    address: "Carrera 1A # 23-45, Torre Salguero Bay",
    zone: "Santa Marta",
    coordinates: { lat: 11.1898, lng: -74.2275 },
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    builtArea: 98,
    privateArea: 90,
    floorNumber: 12,
    yearBuilt: 2024,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Licencia turística comercial",
      "Vista frontal al mar",
      "Piscina infinity en piso 20",
      "Restaurante y room service",
      "Gimnasio de alto rendimiento",
      "Completamente dotado y decorado",
      "Cerraduras electrónicas inteligentes",
      "Salida directa a la arena de Playa Salguero",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "INVERSION_SALGUERO_TURISTICO",
    metaTitle: "Apartamento Turístico con Alta Rentabilidad en Playa Salguero | SERINMOBILIARIO",
    metaDescription:
      "Oportunidad de inversión inmobiliaria en Playa Salguero, Santa Marta. Alta ocupación y administración hotelera.",
    createdAt: "2026-02-18T14:30:00Z",
    updatedAt: "2026-03-05T09:15:00Z",
  },
  {
    id: "prop-3",
    slug: "villa-marina-pozos-colorados",
    code: "SER-318",
    title: "Villa Privada de Playa en Pozos Colorados",
    tagline: "Privacidad, arquitectura bioclimática y jardines tropicales privados",
    description:
      "Exclusiva residencia de una sola planta dentro de condominio cerrado de ultralujo en Pozos Colorados. Diseñada para fundir el interior con el paisaje exterior, cuenta con piscina privada en piedra Bali, área de asados bajo pérgola de teca, 4 suites cada una con vestier y baño privado exterior ajardinado. A pocos pasos de las tranquilas aguas de Pozos Colorados.",
    price: 2890000000,
    currency: "COP",
    adminFee: 1100000,
    operation: "venta",
    propertyType: "casa-playa",
    status: "destacada",
    isFeatured: true,
    sectorId: "sec-pozos-colorados",
    sectorName: "Pozos Colorados",
    address: "Condominio Arenas de Pozos Colorados, Casa 14",
    zone: "Santa Marta",
    coordinates: { lat: 11.1485, lng: -74.2291 },
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 4,
    builtArea: 320,
    privateArea: 540,
    floorNumber: 1,
    yearBuilt: 2022,
    estrato: 6,
    seaView: false,
    pool: true,
    balcony: false,
    elevator: false,
    gym: false,
    furnished: false,
    airConditioning: true,
    privateSecurity: true,
    beachfront: false,
    terrace: true,
    amenities: [
      "Piscina privada tipo espejo de agua",
      "Jardines tropicales privados de 220 m²",
      "Pérgola BBQ y comedor al aire libre",
      "Condominio con canchas de tenis y padel",
      "Acceso privado peatonal a la playa",
      "Seguridad perimetral armada 24/7",
      "Cuarto de servicio completo",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "CASA_PLAYA_POZOS_COLORADOS",
    metaTitle: "Villa Privada de Playa en Pozos Colorados | SERINMOBILIARIO",
    metaDescription:
      "Casa de playa de lujo en Pozos Colorados, Santa Marta. 4 habitaciones, piscina privada y condominio cerrado.",
    createdAt: "2026-01-20T11:00:00Z",
    updatedAt: "2026-02-28T16:00:00Z",
  },
  {
    id: "prop-4",
    slug: "residencia-rodadero-sur-mar",
    code: "SER-415",
    title: "Apartamento Familiar con Vista Plena en Rodadero Sur",
    tagline: "Confort frente a la calma de la bahía con acabados de primera línea",
    description:
      "Situado en el sector más sereno y residencial de El Rodadero, este espacioso apartamento de 3 alcobas goza de una brisa constante y atardeceres dorados ininterrumpidos. Cuenta con cocina integral de cuarzo blanco, balcón social tipo terraza de 18 m² y alcoba principal con vista directa a la bahía. El condominio dispone de piscina para adultos, zona infantil, sauna y muelle recreativo cercano.",
    price: 890000000,
    currency: "COP",
    adminFee: 520000,
    operation: "venta",
    propertyType: "apartamento",
    status: "destacada",
    isFeatured: true,
    sectorId: "sec-el-rodadero",
    sectorName: "El Rodadero y Rodadero Sur",
    address: "Calle 24 # 1-15, Rodadero Sur",
    zone: "Santa Marta",
    coordinates: { lat: 11.2052, lng: -74.2283 },
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    builtArea: 145,
    privateArea: 135,
    floorNumber: 9,
    yearBuilt: 2021,
    estrato: 5,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: false,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Vista frontal a la bahía de El Rodadero",
      "Piscina panorámica y solárium",
      "Balcón amplio para sala de estar exterior",
      "Dos parqueaderos privados cubiertos",
      "Portería y vigilancia 24 horas",
      "Ascensores de última tecnología",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "VENTA_RODADERO_SUR",
    metaTitle: "Apartamento con Vista al Mar en Rodadero Sur | SERINMOBILIARIO",
    metaDescription:
      "Excelente apartamento de 3 alcobas en Rodadero Sur, Santa Marta. Balcón amplio y vista al mar.",
    createdAt: "2026-02-02T08:00:00Z",
    updatedAt: "2026-03-02T10:00:00Z",
  },
  {
    id: "prop-5",
    slug: "loft-boutique-centro-historico",
    code: "SER-190",
    title: "Loft Colonial Restaurado con Terraza Privada en Centro Histórico",
    tagline: "El encanto de 1890 con comodidades contemporáneas a 2 calles de la Marina",
    description:
      "Impresionante loft de doble altura en casa colonial catalogada y meticulosamente restaurada. Muros en mampostería original de calicanto, vigas de madera a la vista, pisos en baldosa hidráulica artesanal y terraza privada con jacuzzi y vistas a las cúpulas de la Catedral y los mástiles de la Marina Internacional. Ideal para residencia de descanso o alquiler boutique selecto.",
    price: 750000000,
    currency: "COP",
    adminFee: 280000,
    operation: "venta",
    propertyType: "apartamento",
    status: "publicada",
    isFeatured: false,
    sectorId: "sec-centro-historico",
    sectorName: "Centro Histórico & Marina",
    address: "Calle de la Iglesia Mayor # 4-22",
    zone: "Santa Marta",
    coordinates: { lat: 11.2415, lng: -74.2105 },
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 0,
    builtArea: 112,
    privateArea: 112,
    floorNumber: 2,
    yearBuilt: 1910,
    estrato: 4,
    seaView: false,
    pool: false,
    balcony: true,
    elevator: false,
    gym: false,
    furnished: true,
    airConditioning: true,
    privateSecurity: false,
    beachfront: false,
    terrace: true,
    amenities: [
      "Techos de doble altura con vigas de madera noble",
      "Terraza privada en azotea con jacuzzi",
      "Mobiliario de anticuario y diseño contemporáneo",
      "Ubicación privilegiada en zona de alta gastronomía",
      "A 300 metros de la Marina Internacional",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "LOFT_CENTRO_HISTORICO",
    metaTitle: "Loft Colonial de Lujo en Centro Histórico | SERINMOBILIARIO",
    metaDescription:
      "Loft patrimonial restaurado con terraza y jacuzzi en el Centro Histórico de Santa Marta.",
    createdAt: "2026-02-10T15:00:00Z",
    updatedAt: "2026-03-08T18:20:00Z",
  },
  {
    id: "prop-6",
    slug: "penthouse-bello-horizonte-arriendo-lujo",
    code: "SER-982",
    title: "Penthouse Exclusivo en Arriendo Mensual en Bello Horizonte",
    tagline: "Lujo por temporadas o contrato anual con servicios hoteleros incluidos",
    description:
      "Disponible para arriendo corporativo o largas temporadas de descanso. Espectacular apartamento amoblado en Bello Horizonte con 3 habitaciones en suite, terraza privada con vista al atardecer sobre el mar, cocina dotada de electrodomésticos de alta gama y acceso a club de playa privado.",
    price: 14500000,
    currency: "COP",
    adminFee: 0,
    operation: "arriendo",
    propertyType: "penthouse",
    status: "publicada",
    isFeatured: false,
    sectorId: "sec-bello-horizonte",
    sectorName: "Bello Horizonte",
    address: "Av. Playa Bello Horizonte # 12-80",
    zone: "Santa Marta",
    coordinates: { lat: 11.135, lng: -74.228 },
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 2,
    builtArea: 210,
    privateArea: 195,
    floorNumber: 15,
    yearBuilt: 2023,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Arriendo completamente amoblado",
      "Vista frontal al mar",
      "Acceso directo a playa privada",
      "Club de playa con carpas y camareros",
      "Gimnasio y spa en el edificio",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "ARRIENDO_BELLO_HORIZONTE",
    metaTitle: "Penthouse en Arriendo en Bello Horizonte | SERINMOBILIARIO",
    metaDescription: "Penthouse de lujo amoblado en arriendo en Bello Horizonte, Santa Marta.",
    createdAt: "2026-02-25T11:00:00Z",
    updatedAt: "2026-03-09T14:10:00Z",
  },
  {
    id: "prop-7",
    slug: "residencia-playa-dormida-bello-horizonte",
    code: "SER-740",
    title: "Residencia Signature Frente al Mar en Playa Dormida",
    tagline: "Arquitectura contemporánea en el sector residencial de mayor exclusividad",
    description:
      "Ubicada en el sector más codiciado de Playa Dormida / Bello Horizonte, esta impresionante residencia cuenta con amplios ventanales de piso a techo, acabados en piedra caliza, cocina italiana con isla central y terraza privada con piscina sinfín orientada hacia los atardeceres del Caribe. Acceso directo a playa privada sin vendedores y servicio de conserjería integral.",
    price: 2450000000,
    currency: "COP",
    adminFee: 1250000,
    operation: "venta",
    propertyType: "apartamento",
    status: "destacada",
    isFeatured: true,
    sectorId: "sec-bello-horizonte",
    sectorName: "Bello Horizonte",
    address: "Corredor Hotelero Km 12, Residencias Playa Dormida",
    zone: "Santa Marta",
    coordinates: { lat: 11.129, lng: -74.23 },
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 2,
    builtArea: 240,
    privateArea: 220,
    floorNumber: 7,
    yearBuilt: 2024,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Salida directa a playa privada",
      "Piscina infinity climatizada",
      "Acabados italianos de ultralujo",
      "Conserjería estilo hotel 5 estrellas",
      "Seguridad privada armada 24/7",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "VENTA_PLAYA_DORMIDA",
    metaTitle: "Residencia Signature en Playa Dormida | SERINMOBILIARIO",
    metaDescription: "Residencia de ultralujo frente al mar en Playa Dormida, Santa Marta.",
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
  },
  {
    id: "prop-8",
    slug: "apartasuite-inversion-pozos-colorados",
    code: "SER-215",
    title: "Apartasuite Panorámico de Inversión en Pozos Colorados",
    tagline: "Alta valorización y rentas turísticas automatizadas con operador hotelero",
    description:
      "Excelente activo de inversión inmobiliaria completamente amoblado y dotado según estándares internacionales. Ubicado en resort condominio de Pozos Colorados con acceso directo a la playa, 4 piscinas temáticas, spa, canchas de pádel y bar de playa. Ideal para quienes buscan generar renta en dólares sin preocuparse por la operación diaria.",
    price: 640000000,
    currency: "COP",
    adminFee: 420000,
    operation: "inversion",
    propertyType: "condohotel",
    status: "publicada",
    isFeatured: false,
    sectorId: "sec-pozos-colorados",
    sectorName: "Pozos Colorados",
    address: "Condominio Sol del Caribe, Torre 2",
    zone: "Santa Marta",
    coordinates: { lat: 11.149, lng: -74.229 },
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 1,
    builtArea: 65,
    privateArea: 58,
    floorNumber: 5,
    yearBuilt: 2023,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Operador hotelero certificado",
      "Alta tasa de ocupación anual",
      "Piscinas tipo laguna y jacuzzis",
      "Canchas de pádel y tenis",
      "Completamente amoblado y decorado",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "INVERSION_POZOS_COLORADOS",
    metaTitle: "Apartasuite de Inversión en Pozos Colorados | SERINMOBILIARIO",
    metaDescription: "Apartasuite amoblado con rentabilidad turística en Pozos Colorados.",
    createdAt: "2026-02-28T14:00:00Z",
    updatedAt: "2026-03-08T16:00:00Z",
  },
  {
    id: "prop-9",
    slug: "penthouse-marina-santa-marta",
    code: "SER-950",
    title: "Penthouse Náutico con Vista a los Yates en Marina Internacional",
    tagline: "Vistas directas a la bahía y a los atracaderos de yates en el corazón samario",
    description:
      "Para los amantes de la vida náutica y el mar. Este penthouse contemporáneo domina la bahía de Santa Marta y la Marina Internacional. Dispone de techos altos, terraza con jacuzzi privado sobre la bahía, ventanería termoacústica y carpintería en roble blanco. El edificio cuenta con piscina semiolímpica, gimnasio con vista panorámica y acceso directo al malecón náutico.",
    price: 1950000000,
    currency: "COP",
    adminFee: 980000,
    operation: "venta",
    propertyType: "penthouse",
    status: "publicada",
    isFeatured: true,
    sectorId: "sec-centro-historico",
    sectorName: "Centro Histórico & Marina",
    address: "Cra 1C # 22-80, Edificio Marina Real",
    zone: "Santa Marta",
    coordinates: { lat: 11.242, lng: -74.212 },
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 2,
    builtArea: 260,
    privateArea: 240,
    floorNumber: 16,
    yearBuilt: 2022,
    estrato: 5,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: true,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Vista frontal a la Marina Internacional",
      "Jacuzzi privado en terraza",
      "Dos parqueaderos privados y depósito náutico",
      "Gimnasio con vista al mar",
      "Piscina panorámica en azotea",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "VENTA_PENTHOUSE_MARINA",
    metaTitle: "Penthouse Náutico en Marina Internacional | SERINMOBILIARIO",
    metaDescription: "Penthouse de lujo frente a la Marina Internacional de Santa Marta.",
    createdAt: "2026-02-12T16:00:00Z",
    updatedAt: "2026-03-07T12:00:00Z",
  },
  {
    id: "prop-10",
    slug: "apartamento-playa-salguero-vista-total",
    code: "SER-610",
    title: "Apartamento de Gran Lujo en Torre Salguero Bay",
    tagline: "Piso alto con vista despejada a la desembocadura y la Sierra Nevada",
    description:
      "Exclusivo apartamento en piso 16 de una de las torres más icónicas de Playa Salguero. Diseñado con una amplia zona social integrada al balcón terraza, alcoba principal con vestier doble y baño en mármol con vista al mar. El conjunto ofrece salida directa a la playa, 3 piscinas, turco, sauna y zona de coworking para ejecutivos.",
    price: 1350000000,
    currency: "COP",
    adminFee: 780000,
    operation: "venta",
    propertyType: "apartamento",
    status: "publicada",
    isFeatured: false,
    sectorId: "sec-playa-salguero",
    sectorName: "Playa Salguero",
    address: "Carrera 1A # 25-10, Playa Salguero",
    zone: "Santa Marta",
    coordinates: { lat: 11.19, lng: -74.227 },
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    builtArea: 155,
    privateArea: 142,
    floorNumber: 16,
    yearBuilt: 2023,
    estrato: 6,
    seaView: true,
    pool: true,
    balcony: true,
    elevator: true,
    gym: true,
    furnished: false,
    airConditioning: true,
    privateSecurity: true,
    beachfront: true,
    terrace: true,
    amenities: [
      "Piso 16 con vista frontal y lateral al mar",
      "Balcón terraza con zona para comedor exterior",
      "Club house con 3 piscinas y sauna",
      "Dos parqueaderos cubiertos",
      "Salida directa a la playa de Salguero",
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=1600&q=80",
    images: [
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80",
    ],
    clientifyTag: "VENTA_SALGUERO_BAY",
    metaTitle: "Apartamento de Gran Lujo en Playa Salguero | SERINMOBILIARIO",
    metaDescription: "Apartamento con vista frontal al mar en Playa Salguero, Santa Marta.",
    createdAt: "2026-02-22T10:00:00Z",
    updatedAt: "2026-03-09T17:00:00Z",
  },
];
